<a href="https://colab.research.google.com/github/kuznechek/Numerical-methods/blob/main/MethodOfFletcherReeves.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Метод Флетчера-Ривса

In [ ]:
import torch

def function(w):
  w1 = w[0] 
  w2 = w[1]
  w3 = w[2]
  result = 3 *w1**2 + w2**2 + 5*w3**2 - w1*w2 + 2*w1*w3 + 6*w1 - 5*w2
  return result

def partial_der(w):
  w1 = w[0] 
  w2 = w[1]
  w3 = w[2]
  v = (6*w1 + w2 + 7*w3 + 1) / 12
  return v + 0.001

x = torch.tensor([0.125, 2.625, -0.625], requires_grad = True)
print('Начальные координаты : X =', x)
print('')
k = 0
norma = 10.
while 1:
  fx = function(x)
  x.requires_grad_(True)
  fx.backward()
  gx = x.grad
  print(x)
  print(gx)
  print(torch.norm(gx))
  if torch.norm(gx) < 0.1:
    break
  if k == 0:
    d = -gx
    print('D =',d)
  else:
    b1 = torch.norm(gx)/torch.norm(d)
    d = gx + b*g1
    t = partial_der(x)
    x = x.data + t*d
    #print('d =', d)
    #print('t =', t)
    print('X* =', x)
    print('')
    #break
  k += 1
print('Количество итераций :', k)
print('X* =', x)

Начальные координаты : X = tensor([ 0.1250,  2.6250, -0.6250], requires_grad=True)

tensor([ 0.1250,  2.6250, -0.6250], requires_grad=True)
tensor([ 2.8750,  0.1250, -6.0000])
tensor(6.6544)
D = tensor([-2.8750, -0.1250,  6.0000])
tensor([ 0.1250,  2.6250, -0.6250], requires_grad=True)
tensor([  5.7500,   0.2500, -12.0000])
tensor(13.3088)
X* = tensor([ 0.0507,  2.6112, -0.7492], grad_fn=<AddBackward0>)

tensor([ 0.0507,  2.6112, -0.7492], grad_fn=<AddBackward0>)
None


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:26: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.


AttributeError: ignored